### ISSUE TITLE
Python 3.7 suport - Google colab related

### ISSUE THREAD

**Issue by tvercaut** [cornellius-gp/linear_operator#20]
Hi,

Thanks for the nice library. I just saw the package on pypi (https://pypi.org/project/linear-operator/) and wanted to quickly try it with Google colab (with currently runs python 3.7.14) but haven't managed to get it setup yet due to the required python version being >=3.8:
https://github.com/cornellius-gp/linear_operator/blob/main/setup.py

Would it be possible to relax the python requirements to support running on google colab?

For the record, the error message was also rather difficult to read:
```
!pip install linear-operator
```
led to 
```
ERROR: Could not find a version that satisfies the requirement linear-operator (from versions: none)
```
while a more explicit command was a bit more readable:
```
!pip install https://files.pythonhosted.org/packages/e6/3c/a2cbf56429c4e370cdcd76155fc1068d21a812c67655244f0776a27697c7/linear_operator-0.1.1-py3-none-any.whl
```
led to
```
ERROR: Package 'linear-operator' requires a different Python: 3.7.14 not in '>=3.8'
```

Best,
Tom

**Comment by Balandat** [comment]
Is colab still on 3.7? Those guys, even new releases of numpy have dropped py3.7 support at this point. 

To your question: This would likely require a bit of work (@gpleiss will have more context), so ideally we can avoid this especially since all other numerical/scientific python packages are dropping 3.7 support.

**Comment by tvercaut** [comment]
Ok, thanks. I'll close this issue then. In the meantime, I realised that some of the features I was interested are in GpyTorch 1.8.1 (see https://github.com/cornellius-gp/gpytorch/tree/v1.8.1/gpytorch/utils) which works on colab so I'll stick to that for now.
