### ISSUE TITLE
Upgrade required typeguard version

### ISSUE THREAD

**Issue by melanopsis** [cornellius-gp/linear_operator#84]
Greetings, 

LinearOperator seems to require `typeguard~=2.13.3`, which is from December 2021 and typeguard is currently at v4.1.5. It would be nice to upgrade this dependency to something more recent. 

Thank you.

**Comment by tmct** [comment]
Would be great to see recent typeguard supported please - this upper bound causes us great trouble concurrently satisfying dependencies with other packages. Thanks
